name: Build Windows

on:
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
    # - uses: actions/checkout@v3
    # - run: git fetch --prune --unshallow

    - name: Checkout
      uses: actions/checkout@v4

    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: 'npm'

    - name: Install Dependencies
      run: |
        cd app
        mkdir db
        dir && xcopy /Y "./config/sql.db" "./db"
        cd ..
        npm i --save-dev
        # cd webui
        # npm i --legacy-peer-deps --save-dev
    - name: Eslint
      run: |
        npm run eslint
        # cd webui
        # npm run eslint
    # - name: Prepare Theme Files
    #   working-directory: ./webui
    #   run: |
    #     mkdir ./public/assets/styles
    #     node dark
    #     node light
    #     node cyber

    # - name: Build Static Files
    #   working-directory: ./webui
    #   run: |
    #     npm run build
