name: Build Windows

on:
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: 'Vertex'
        
    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: 'npm'

    - name: Install Dependencies
      run: |
        pwd
        dir
        cd Vertex
        dir
        rd /s /q .\webui
        cd app
        mkdir db
        xcopy /Y "./config/sql.db" "./db"
        cd ..
        dir
        npm i --save-dev
        # cd webui
        # npm i --legacy-peer-deps --save-dev

    - name: build
      run: |
        mkdir webui
        dir
        mv ./Vertex/app/static/* ./webui/
        cd webui
        dir
    - name: Install Inno Setup Compiler
      uses: pwall2222/inno-setup-download@v0.0.4
      
    - name: COPY NODE
      run: |
        pwd
        dir
        mkdir Node14
        cd Node14
        Copy-Item -Path "C:\hostedtoolcache\windows\node\14.21.3\x64\*" -Destination .
        dir

    - name: 拉取exe代码
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PRIVATE_REPO_TOKEN }}
        ref: windows
        repository: ${{ secrets.REPO }}
        ssh-key: ${{ secrets.DEPLOY_KEY }}
        path: 'Inno-Setup-Vertex'

    - name: Compile Inno Setup Script
      run: |
        dir
        cd Inno-Setup-Vertex
        Copy-Item -Path ".\ChineseSimplified.isl" -Destination "C:\Users\runneradmin\AppData\Local\Temp\inno\Languages"
        iscc "/DMyAppVersion=0.0.1" build.iss

    # - name: Prepare Theme Files
    #   working-directory: ./webui
    #   run: |
    #     mkdir ./public/assets/styles
    #     node dark
    #     node light
    #     node cyber

    # - name: Build Static Files
    #   working-directory: ./webui
    #   run: |
    #     npm run build
